name: InfraPatch Github Action
description: A github action to update provider and module dependencies in terraform files
author: "Noah Canadea"
inputs:
  target_branch_name:
    description: "Name of the branch where changes will be pushed to. Defaults to feature/infrapatch-bot"
    required: true
    default: "feature/infrapatch-bot"
  repository_name:
    description: "Name of the repository to run the action in. Defaults to the current repository"
    required: false
    default: ${{ github.repository }}
  default_registry_domain:
    description: "Default registry domain to use for modules and providers without explicit registry domain set. Defaults to registry.terraform.io"
    required: false
    default: "registry.terraform.io"
  git_user:
    description: "Git user to use for commits. Defaults to InfraPatch Bot"
    required: false
    default: "InfraPatch Bot"
  git_email:
    description: "Git email to use for commits. Defaults to bot@infrapatch.ch"
    required: false
    default: "bot@infrapatch.ch"
  github_token:
    description: "GitHub access token. Defaults to github.token."
    default: ${{ github.token }}
  report_only:
    description: "Only report new versions. Do not update files. Defaults to false"
    default: "false"
    required: true
  registry_secrets:
    description: "Registry secrets to use for private registries"
    required: false
    default: ""
  working_directory:
    description: "Working directory to run the command in. Defaults to the root of the repository"
    required: false
    default: ${{ github.workspace }}
outputs:
  target_branch:
    description: "Name of the branch where changes will be pushed to"
    value: ${{ inputs.target_branch_name }}

runs:
  using: composite
  steps:
    - name: Extract branch name
      id: branch
      shell: bash
      run: |
        head_branch_origin="origin/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        head_branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        target_branch="${{ inputs.target_branch_name }}"
        target_branch_origin="origin/${{ inputs.target_branch_name }}"
        echo "Using head branch $head_branch and target branch $target_branch"
        echo "head=$head_branch" >> $GITHUB_OUTPUT
        echo "head_origin=$head_branch_origin" >> $GITHUB_OUTPUT
        echo "target=$target_branch" >> $GITHUB_OUTPUT
        echo "target_origin=$target_branch_origin" >> $GITHUB_OUTPUT

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Create target branch
      id: create_branch
      if: ${{ inputs.report_only == 'false' }}
      uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        branch: "refs/heads/${{ inputs.target_branch_name }}"

    - name: Configure git
      if: ${{ inputs.report_only }} == 'false' }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        git config --global user.name "${{ inputs.git_user }}"
        git config --global user.email "${{ inputs.git_email }}"

    - name: Switch to target branch
      if: ${{ inputs.report_only == 'false' }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        git fetch origin
        git checkout -b "${{ steps.branch.outputs.target }}" "${{ steps.branch.outputs.target_origin }}"

    - name: Rebase target branch
      if: ${{ steps.create_branch.outputs.created == 'false' }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        echo "Rebasing ${{ steps.branch.outputs.target }} on ${{ steps.branch.outputs.head_origin }}"
        git rebase -Xtheirs ${{ steps.branch.outputs.head_origin }}

    - name: Run InfraPatch Action
      shell: bash
      run: |
        module="infrapatch.action"
        arguments=()
        if [ "${{ runner.debug }}" == "1" ]; then
            arguments+=("--debug")
        fi
        if [ "${{ inputs.report_only }}" == "true" ]; then
            arguments+=("--report-only")
        fi
        if [ "${{ inputs.registry_secrets }}" != "" ]; then
            arguments+=("--registry-secrets-string" "\"${{ inputs.registry_secrets }}\"")
        fi
        arguments+=("--github-token" "${{ inputs.github_token }}")
        arguments+=("--head-branch" "${{ steps.branch.outputs.head }}")
        arguments+=("--target-branch" "${{ steps.branch.outputs.target }}")
        arguments+=("--repository-name" "${{ inputs.repository_name }}")
        arguments+=("--working-directory" "${{ inputs.working_directory }}")
        arguments+=("--default-registry-domain" "${{ inputs.default_registry_domain }}")
        python -m "$module" "${arguments[@]}"

